-- hypr-look.lua — MACHINE-GENERATED by `luminos-look save`. Do not hand-edit.
-- [CHANGE: claude-code | 2026-08-04]
--
-- This file is overwritten WHOLE on every save. Hand-written variable overrides belong
-- in hypr-vars.lua, which merges this file over itself — that split is what keeps a
-- save from ever clobbering the app / cursor / suspend settings.
--
-- preset: custom
-- saved : 2026-08-04T18:22:43-04:00

return {
    windowRounding      = 15,
    windowGapsIn        = 5,
    windowGapsOut       = 10,
    singleWindowGapsOut = 10,
    workspaceGaps       = 10,
    windowBorderSize    = 1,
    windowOpacity       = 0.95,

    blurEnabled         = true,
    blurSize            = 8,
    blurPasses          = 2,
    blurXray            = false,

    shadowEnabled       = true,
    shadowRange         = 15,

    luminosAnimations   = true,
    luminosLookPreset   = "custom",
}
