"""
src/gui/theme/gtk_css.py
Generates the master GTK4 CSS string from color and spacing values.

Rules:
- All values injected from colors.py and spacing.py — no hardcoded magic.
- Returns a complete CSS string ready to load via Gtk.CssProvider.
- Compatible with GTK4 + libadwaita; backdrop-filter requires compositor support.
- generate_css() is pure — no I/O, no side effects.
"""

from .colors  import get_colors
from .spacing import RADIUS, SPACING, SIZING, ANIMATION


def generate_css(dark: bool = True) -> str:
    """
    Generate the complete Luminos GTK4 CSS string.

    Args:
        dark: True for dark mode, False for light mode.

    Returns:
        Complete CSS string.
    """
    c = get_colors(dark)
    r = RADIUS
    s = SPACING
    z = SIZING
    a = ANIMATION

    return f"""\
/* =========================================================
   Luminos GTK4 Master Stylesheet
   Mode: {"dark" if dark else "light"}
   Generated by src/gui/theme/gtk_css.py — do not edit directly
   ========================================================= */

/* --- GTK color variable definitions --- */
@define-color accent_color {c["accent_blue"]};
@define-color accent_bg_color {c["accent_blue"]};
@define-color accent_fg_color #ffffff;
@define-color window_bg_color {c["bg_primary"]};
@define-color window_fg_color {c["text_primary"]};
@define-color view_bg_color {c["bg_secondary"]};
@define-color view_fg_color {c["text_primary"]};
@define-color headerbar_bg_color {c["bg_secondary"]};
@define-color headerbar_fg_color {c["text_primary"]};
@define-color card_bg_color {c["surface_raised"]};
@define-color card_fg_color {c["text_primary"]};
@define-color popover_bg_color {c["surface_overlay"]};
@define-color popover_fg_color {c["text_primary"]};
@define-color sidebar_bg_color {c["bg_secondary"]};
@define-color sidebar_fg_color {c["text_primary"]};

/* --- Base window --- */
window {{
  background-color: {c["bg_primary"]};
  color: {c["text_primary"]};
  font-family: "Inter", "SF Pro Display", "Segoe UI", system-ui, sans-serif;
  font-size: 13px;
}}

/* --- Frosted glass panel --- */
.luminos-panel {{
  background: {c["surface"]};
  backdrop-filter: blur(20px) saturate(180%);
  -webkit-backdrop-filter: blur(20px) saturate(180%);
  border: 1px solid {c["border"]};
  border-radius: {r["large"]}px;
}}

/* --- Top bar --- */
.luminos-bar {{
  background: {c["bar_bg"]};
  backdrop-filter: blur(24px) saturate(200%);
  -webkit-backdrop-filter: blur(24px) saturate(200%);
  border-bottom: 1px solid {c["border"]};
  min-height: {z["bar_height"]}px;
  padding: 0 {s["md"]}px;
}}

/* --- Dock --- */
.luminos-dock {{
  background: {c["dock_bg"]};
  backdrop-filter: blur(20px) saturate(180%);
  -webkit-backdrop-filter: blur(20px) saturate(180%);
  border: 1px solid {c["border"]};
  border-radius: {r["xlarge"]}px;
  padding: {s["sm"]}px {s["md"]}px;
}}

.luminos-dock-item {{
  border-radius: {r["large"]}px;
  min-width: {z["dock_icon"]}px;
  min-height: {z["dock_icon"]}px;
  padding: {s["xs"]}px;
  transition: all {a["fast"]}ms ease-out;
}}

.luminos-dock-item:hover {{
  background: {c["dock_item_hover"]};
  min-width: {z["dock_icon_hover"]}px;
  min-height: {z["dock_icon_hover"]}px;
}}

/* --- Standard button --- */
button.luminos-btn {{
  background: transparent;
  border: 1px solid {c["border"]};
  border-radius: {r["medium"]}px;
  color: {c["text_primary"]};
  padding: {s["sm"]}px {s["md"]}px;
  transition: all {a["fast"]}ms ease-out;
}}

button.luminos-btn:hover {{
  background: {c["border"]};
}}

button.luminos-btn:active {{
  background: {c["border_strong"]};
}}

/* --- Accent button --- */
button.luminos-btn-accent {{
  background: {c["accent_blue"]};
  border: none;
  color: #ffffff;
  border-radius: {r["medium"]}px;
  padding: {s["sm"]}px {s["lg"]}px;
  transition: all {a["fast"]}ms ease-out;
}}

button.luminos-btn-accent:hover {{
  background: {c["accent_blue_hover"]};
}}

/* --- Input fields --- */
entry.luminos-input {{
  background: {c["surface_raised"]};
  border: 1px solid {c["border"]};
  border-radius: {r["medium"]}px;
  color: {c["text_primary"]};
  padding: {s["sm"]}px {s["md"]}px;
  transition: border-color {a["fast"]}ms ease-out;
}}

entry.luminos-input:focus {{
  border-color: {c["accent_blue"]};
  box-shadow: 0 0 0 3px rgba(10,132,255,0.25);
}}

entry.luminos-input placeholder {{
  color: {c["text_tertiary"]};
}}

/* --- Zone badges --- */
.zone-badge-2 {{
  background: {c["zone2_wine"]};
  color: #ffffff;
  border-radius: {r["pill"]}px;
  font-size: 10px;
  font-weight: 600;
  padding: 2px 6px;
}}

.zone-badge-3 {{
  background: {c["zone3_alert"]};
  color: #ffffff;
  border-radius: {r["pill"]}px;
  font-size: 10px;
  font-weight: 600;
  padding: 2px 6px;
}}

/* --- Sentinel status indicators --- */
.sentinel-safe   {{ color: {c["sentinel_safe"]};   }}
.sentinel-warn   {{ color: {c["sentinel_warn"]};   }}
.sentinel-danger {{ color: {c["sentinel_danger"]}; }}

/* --- AI status indicator --- */
.luminos-ai-status {{
  color: {c["luminos_ai"]};
  font-size: 12px;
  font-weight: 500;
}}

/* --- Card / surface panel --- */
.luminos-card {{
  background: {c["surface_raised"]};
  border: 1px solid {c["border"]};
  border-radius: {r["large"]}px;
  padding: {s["lg"]}px;
}}

/* --- Secondary text --- */
.text-secondary {{
  color: {c["text_secondary"]};
}}

.text-tertiary {{
  color: {c["text_tertiary"]};
}}

.text-disabled {{
  color: {c["text_disabled"]};
}}

/* --- Status colors --- */
.status-success {{ color: {c["success"]}; }}
.status-warning {{ color: {c["warning"]}; }}
.status-error   {{ color: {c["error"]};   }}
.status-info    {{ color: {c["info"]};    }}

/* --- Scrollbars — thin macOS style --- */
scrollbar {{
  background: transparent;
  border: none;
  min-width: 6px;
  min-height: 6px;
}}

scrollbar slider {{
  background: {c["text_tertiary"]};
  border-radius: {r["pill"]}px;
  min-width: 6px;
  min-height: 20px;
}}

scrollbar slider:hover {{
  background: {c["text_secondary"]};
}}

/* --- Separator --- */
separator {{
  background: {c["border"]};
  min-height: 1px;
  min-width: 1px;
}}
"""
