// [CHANGE: claude-code | 2026-06-14]
// luminos-theme-gen — the keystone of UI cohesion.
//
// Single source of truth: design/luminos-tokens.json (+ its QML mirror
// src/theme/Theme.qml, edited together). This tool fans those tokens out to
// every toolkit so colors/radii/fonts can never drift apart by hand:
//
//   1. Copies src/theme/Theme.qml verbatim into each self-contained package
//      (Plasma plasmoids + the HIVE app) so QML consumers stay runtime-self-
//      contained (no cross-module QML import-path dependency).
//   2. Generates config/kde/colors/Luminos.colors  (Qt/KDE apps).
//   3. Generates config/gtk-3.0/gtk.css + gtk-4.0/gtk.css  (GTK + libadwaita
//      named-accent overrides — the only lever that reaches libadwaita).
//
// Usage:  go run . [-repo /home/shawn/luminos-os] [-check]
// Build:  go build -o luminos-theme-gen .   (run AFTER training; no runtime deps)
//
// NOTE: this tool only writes repo files. It does NOT apply anything live
// (no kwriteconfig6, no plasmashell/kwin reload). Deploy/apply is a separate step.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

type tokens struct {
	Version string            `json:"version"`
	Color   map[string]string `json:"color"`
}

// Plasma packages + apps that get a co-located copy of Theme.qml.
var qmlConsumers = []string{
	"src/widgets/org.luminos.powerwidget/contents/ui/Theme.qml",
	"src/widgets/org.luminos.ramwidget/contents/ui/Theme.qml",
	"src/hive/Theme.qml",
}

func main() {
	repo := flag.String("repo", ".", "path to the luminos-os repo root")
	check := flag.Bool("check", false, "verify outputs are up to date; exit 1 if not (no writes)")
	flag.Parse()

	tokPath := filepath.Join(*repo, "design", "luminos-tokens.json")
	raw, err := os.ReadFile(tokPath)
	must(err, "read tokens")

	var t tokens
	must(json.Unmarshal(raw, &t), "parse tokens json")
	if t.Color == nil {
		fatal("tokens json missing 'color' map")
	}

	canonicalQML := filepath.Join(*repo, "src", "theme", "Theme.qml")
	qmlSrc, err := os.ReadFile(canonicalQML)
	must(err, "read canonical Theme.qml")

	colors := genColors(t)
	gtk := genGTKCSS(t)

	type out struct {
		path string
		data []byte
	}
	outputs := []out{
		{filepath.Join(*repo, "config", "kde", "colors", "Luminos.colors"), []byte(colors)},
		{filepath.Join(*repo, "config", "gtk-3.0", "gtk.css"), []byte(gtk)},
		{filepath.Join(*repo, "config", "gtk-4.0", "gtk.css"), []byte(gtk)},
	}
	for _, rel := range qmlConsumers {
		outputs = append(outputs, out{filepath.Join(*repo, rel), qmlSrc})
	}

	stale := false
	for _, o := range outputs {
		if *check {
			cur, _ := os.ReadFile(o.path)
			if string(cur) != string(o.data) {
				fmt.Printf("STALE: %s\n", o.path)
				stale = true
			}
			continue
		}
		must(os.MkdirAll(filepath.Dir(o.path), 0o755), "mkdir "+o.path)
		must(os.WriteFile(o.path, o.data, 0o644), "write "+o.path)
		fmt.Printf("wrote %s\n", o.path)
	}
	if *check && stale {
		os.Exit(1)
	}
}

// hexRGB turns "#RRGGBB" into "r,g,b" (Breeze .colors format).
func hexRGB(hex string) string {
	h := strings.TrimPrefix(strings.TrimSpace(hex), "#")
	if len(h) != 6 {
		fatal("expected #RRGGBB, got " + hex)
	}
	r, _ := strconv.ParseInt(h[0:2], 16, 0)
	g, _ := strconv.ParseInt(h[2:4], 16, 0)
	b, _ := strconv.ParseInt(h[4:6], 16, 0)
	return fmt.Sprintf("%d,%d,%d", r, g, b)
}

func genColors(t tokens) string {
	c := t.Color
	// Breeze color-scheme block shared by most groups.
	commonAccent := func(bgNormal, bgAlt string) string {
		return strings.Join([]string{
			"BackgroundAlternate=" + hexRGB(bgAlt),
			"BackgroundNormal=" + hexRGB(bgNormal),
			"DecorationFocus=" + hexRGB(c["accent"]),
			"DecorationHover=" + hexRGB(c["accent"]),
			"ForegroundActive=" + hexRGB(c["accent"]),
			"ForegroundInactive=" + hexRGB(c["textSecondary"]),
			"ForegroundLink=" + hexRGB(c["accent"]),
			"ForegroundNegative=" + hexRGB(c["error"]),
			"ForegroundNeutral=" + hexRGB(c["warning"]),
			"ForegroundNormal=" + hexRGB(c["textPrimary"]),
			"ForegroundPositive=" + hexRGB(c["success"]),
			"ForegroundVisited=" + hexRGB(c["accentPressed"]),
		}, "\n")
	}
	var b strings.Builder
	b.WriteString("# GENERATED by scripts/luminos-theme-gen from design/luminos-tokens.json — DO NOT EDIT.\n")
	b.WriteString("# Apply (AFTER training, not mid-run): copy to ~/.local/share/color-schemes/Luminos.colors\n")
	b.WriteString("# then set ColorScheme=Luminos in kdeglobals [General] + reload.\n")
	b.WriteString("[ColorEffects:Disabled]\nColor=" + hexRGB(c["textDisabled"]) + "\nColorAmount=0\nColorEffect=0\nContrastAmount=0.65\nContrastEffect=1\nIntensityAmount=0.1\nIntensityEffect=2\n\n")
	b.WriteString("[Colors:Button]\n" + commonAccent(c["surfaceElevated"], c["surface"]) + "\n\n")
	b.WriteString("[Colors:Complementary]\n" + commonAccent(c["bgBase"], c["surface"]) + "\n\n")
	b.WriteString("[Colors:Header]\n" + commonAccent(c["surfaceElevated"], c["surface"]) + "\n\n")
	b.WriteString("[Colors:Selection]\n" + strings.Join([]string{
		"BackgroundAlternate=" + hexRGB(c["accentPressed"]),
		"BackgroundNormal=" + hexRGB(c["accent"]),
		"DecorationFocus=" + hexRGB(c["accent"]),
		"DecorationHover=" + hexRGB(c["accent"]),
		"ForegroundActive=" + hexRGB(c["textPrimary"]),
		"ForegroundInactive=" + hexRGB(c["textSecondary"]),
		"ForegroundLink=" + hexRGB(c["textPrimary"]),
		"ForegroundNegative=" + hexRGB(c["error"]),
		"ForegroundNeutral=" + hexRGB(c["warning"]),
		"ForegroundNormal=" + hexRGB(c["textPrimary"]),
		"ForegroundPositive=" + hexRGB(c["success"]),
		"ForegroundVisited=" + hexRGB(c["textPrimary"]),
	}, "\n") + "\n\n")
	b.WriteString("[Colors:Tooltip]\n" + commonAccent(c["surfaceElevated"], c["surface"]) + "\n\n")
	b.WriteString("[Colors:View]\n" + commonAccent(c["bgBase"], c["surface"]) + "\n\n")
	b.WriteString("[Colors:Window]\n" + commonAccent(c["surface"], c["surfaceElevated"]) + "\n\n")
	b.WriteString("[General]\nName=Luminos\nshadeSortColumn=true\n\n")
	b.WriteString("[WM]\n" + strings.Join([]string{
		"activeBackground=" + hexRGB(c["surface"]),
		"activeBlend=" + hexRGB(c["textPrimary"]),
		"activeForeground=" + hexRGB(c["textPrimary"]),
		"inactiveBackground=" + hexRGB(c["bgBase"]),
		"inactiveBlend=" + hexRGB(c["textSecondary"]),
		"inactiveForeground=" + hexRGB(c["textSecondary"]),
	}, "\n") + "\n")
	return b.String()
}

func genGTKCSS(t tokens) string {
	c := t.Color
	return fmt.Sprintf(`/* GENERATED by scripts/luminos-theme-gen from design/luminos-tokens.json — DO NOT EDIT. */
/* Apply (AFTER training): copy to ~/.config/gtk-3.0/gtk.css and ~/.config/gtk-4.0/gtk.css. */
/* @define-color accent overrides are the ONLY theming lever that reaches libadwaita apps. */
@define-color accent_color %s;
@define-color accent_bg_color %s;
@define-color accent_fg_color %s;
@define-color theme_selected_bg_color %s;
@define-color theme_selected_fg_color %s;
@define-color success_color %s;
@define-color warning_color %s;
@define-color error_color %s;
@define-color destructive_color %s;
`,
		c["accent"], c["accent"], c["textPrimary"],
		c["accent"], c["textPrimary"],
		c["success"], c["warning"], c["error"], c["error"],
	)
}

func must(err error, ctx string) {
	if err != nil {
		fatal(ctx + ": " + err.Error())
	}
}

func fatal(msg string) {
	fmt.Fprintln(os.Stderr, "luminos-theme-gen: "+msg)
	os.Exit(1)
}
