[General]
DefaultSession=plasma.desktop
RememberLastSession=false
RememberLastUser=true

[Theme]
Current=breeze
CursorTheme=breeze_cursors
Font=Noto Sans,10,-1,5,50,0,0,0,0,0

[Users]
MaximumUid=60000
MinimumUid=1000

[Wayland]
EnableHiDPI=true
ServerArguments=-scale 2
