"""
compositor_config.py
Generates Sway and Waybar configuration for Luminos compositor layer.

Rules:
- generate_sway_config() is pure — returns a string, touches no files.
- write_config() is the only file-writing function.
- Zone 2 XWayland windows get blue borders.
- Zone 3 windows get red borders + QUARANTINE title marker.
- Config targets Hyprland on Arch Linux with luminos-ai.service.
"""

import logging
import os

logger = logging.getLogger("luminos-ai.compositor.config")


def generate_sway_config(output_name: str = "eDP-1") -> str:
    """
    Generate a Sway config string tuned for Luminos.

    Args:
        output_name: Wayland output connector name (e.g. "eDP-1", "HDMI-A-1").

    Returns:
        Multi-line Sway config string.
    """
    return f"""\
# Luminos Sway Configuration
# Auto-generated by luminos compositor_config.py
# DO NOT edit manually — regenerate via luminos-ai compositor tools

# --- Output ---
output {output_name} scale 1

# --- Input ---
input * {{
    natural_scroll enabled
    tap enabled
}}

# --- Appearance ---
gaps inner 8
gaps outer 4
default_border pixel 2
font pango:monospace 10

# --- Zone 2: Wine/XWayland windows (blue border) ---
# Applied by window class set via XWayland bridge
for_window [shell="xwayland"] border pixel 2
for_window [shell="xwayland"] client.focused #0055ff #0055ff #ffffff #0055ff #0055ff

# --- Zone 3: Quarantine VM windows (red border + title warning) ---
for_window [title=".*QUARANTINE.*"] border pixel 4
for_window [title=".*QUARANTINE.*"] client.focused #ff0000 #ff0000 #ffffff #ff0000 #ff0000

# --- Luminos AI Daemon ---
exec luminos-ai

# --- Key bindings ---
set $mod Mod4
bindsym $mod+q kill
bindsym $mod+Return exec foot
bindsym $mod+d exec rofi -show run
bindsym $mod+Shift+e exit

# --- Workspaces ---
bindsym $mod+1 workspace number 1
bindsym $mod+2 workspace number 2
bindsym $mod+3 workspace number 3
bindsym $mod+4 workspace number 4
bindsym $mod+Shift+1 move container to workspace number 1
bindsym $mod+Shift+2 move container to workspace number 2
bindsym $mod+Shift+3 move container to workspace number 3
bindsym $mod+Shift+4 move container to workspace number 4

# --- Window movement ---
bindsym $mod+Left  focus left
bindsym $mod+Right focus right
bindsym $mod+Up    focus up
bindsym $mod+Down  focus down
bindsym $mod+Shift+Left  move left
bindsym $mod+Shift+Right move right
bindsym $mod+Shift+Up    move up
bindsym $mod+Shift+Down  move down

# --- Status bar ---
bar {{
    swaybar_command waybar
}}
"""


def write_config(path: str = "~/.config/sway/config") -> dict:
    """
    Write the generated Sway config to disk.

    Args:
        path: Destination file path (tilde expanded).

    Returns:
        {"success": bool, "path": str, "error": str|None}
    """
    expanded = os.path.expanduser(path)
    try:
        os.makedirs(os.path.dirname(expanded), exist_ok=True)
        content = generate_sway_config()
        with open(expanded, "w") as f:
            f.write(content)
        logger.info(f"Sway config written to {expanded}")
        return {"success": True, "path": expanded, "error": None}
    except OSError as e:
        logger.error(f"Failed to write sway config to {expanded}: {e}")
        return {"success": False, "path": expanded, "error": str(e)}


def generate_waybar_config() -> dict:
    """
    Generate a minimal Waybar config dict for Luminos.

    Returns:
        Waybar JSON-serialisable config dict with left/center/right modules.
    """
    return {
        "layer":    "top",
        "position": "top",
        "height":   30,
        "modules-left":   ["sway/workspaces"],
        "modules-center": ["clock"],
        "modules-right":  [
            "luminos/ai-status",
            "cpu",
            "memory",
            "battery",
        ],
        "clock": {
            "format": "%Y-%m-%d %H:%M",
            "tooltip": False,
        },
        "cpu": {
            "format": "CPU {usage}%",
            "interval": 5,
        },
        "memory": {
            "format": "RAM {}%",
            "interval": 10,
        },
        "battery": {
            "format":          "BAT {capacity}%",
            "format-charging": "CHG {capacity}%",
            "states": {"warning": 20, "critical": 10},
        },
    }
