"""
compositor_config.py
Generates Hyprland and Waybar configuration for Luminos compositor layer.

Rules:
- generate_hyprland_config() is pure — returns a string, touches no files.
- write_config() is the only file-writing function.
- Zone 2 XWayland windows get blue borders.
- Zone 3 windows get red borders + QUARANTINE title marker.
- Config targets Hyprland on Arch Linux with luminos-ai.service.
"""

import logging
import os

logger = logging.getLogger("luminos-ai.compositor.config")


def generate_hyprland_config(output_name: str = "eDP-1") -> str:
    """
    Generate a Hyprland config string tuned for Luminos.

    Args:
        output_name: Wayland output connector name (e.g. "eDP-1", "HDMI-A-1").

    Returns:
        Multi-line Hyprland config string.
    """
    return f"""\
# Luminos Hyprland Configuration
# Auto-generated by luminos compositor_config.py
# DO NOT edit manually — regenerate via luminos-ai compositor tools

# --- Monitor ---
monitor = {output_name}, preferred, auto, 1

# --- Input ---
input {{
    kb_layout = us
    follow_mouse = 1
    sensitivity = 0
    touchpad {{
        natural_scroll = true
        tap-to-click = true
        disable_while_typing = true
        scroll_factor = 0.8
    }}
}}

# --- Appearance ---
general {{
    gaps_in = 8
    gaps_out = 4
    border_size = 2
    col.active_border = rgba(0a84ffee) rgba(5e9effee) 45deg
    col.inactive_border = rgba(ffffff15)
    layout = dwindle
}}

decoration {{
    rounding = 12
    blur {{
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
    }}
    shadow {{
        enabled = yes
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }}
    active_opacity = 1.0
    inactive_opacity = 0.95
    dim_inactive = true
    dim_strength = 0.08
}}

animations {{
    enabled = true
    bezier = overshot, 0.05, 0.9, 0.1, 1.05
    bezier = smoothIn, 0.25, 1, 0.5, 1
    animation = windows, 1, 4, overshot, slide
    animation = fade, 1, 4, smoothIn
    animation = workspaces, 1, 4, overshot, slidevert
}}

dwindle {{
    pseudotile = true
    preserve_split = true
}}

misc {{
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
}}

# --- Zone 2: Wine/XWayland windows (blue border) ---
windowrulev2 = bordercolor rgba(0055ffee), xwayland:1

# --- Zone 3: Quarantine VM windows (red border + thick) ---
windowrulev2 = bordercolor rgba(ff0000ee), title:^(.*QUARANTINE.*)$
windowrulev2 = bordersize 4, title:^(.*QUARANTINE.*)$

# --- Luminos AI Daemon ---
exec-once = luminos-ai

# --- Key bindings ---
$mod = SUPER

bind = $mod, Q, killactive
bind = $mod, Return, exec, foot
bind = $mod, Space, exec, wofi --show drun
bind = $mod SHIFT, E, exit
bind = $mod SHIFT, R, exec, hyprctl reload

# --- Workspaces ---
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4

# --- Window movement ---
bind = $mod, left, movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up, movefocus, u
bind = $mod, down, movefocus, d
bind = $mod SHIFT, left, movewindow, l
bind = $mod SHIFT, right, movewindow, r
bind = $mod SHIFT, up, movewindow, u
bind = $mod SHIFT, down, movewindow, d

# --- Status bar ---
exec-once = waybar
"""


# Keep backward compat alias
generate_sway_config = generate_hyprland_config


def write_config(path: str = "~/.config/hypr/hyprland.conf") -> dict:
    """
    Write the generated Hyprland config to disk.

    Args:
        path: Destination file path (tilde expanded).

    Returns:
        {"success": bool, "path": str, "error": str|None}
    """
    expanded = os.path.expanduser(path)
    try:
        os.makedirs(os.path.dirname(expanded), exist_ok=True)
        content = generate_hyprland_config()
        with open(expanded, "w") as f:
            f.write(content)
        logger.info(f"Hyprland config written to {expanded}")
        return {"success": True, "path": expanded, "error": None}
    except OSError as e:
        logger.error(f"Failed to write Hyprland config to {expanded}: {e}")
        return {"success": False, "path": expanded, "error": str(e)}


def generate_waybar_config() -> dict:
    """
    Generate a minimal Waybar config dict for Luminos.

    Returns:
        Waybar JSON-serialisable config dict with left/center/right modules.
    """
    return {
        "layer":    "top",
        "position": "top",
        "height":   30,
        "modules-left":   ["hyprland/workspaces"],
        "modules-center": ["clock"],
        "modules-right":  [
            "luminos/ai-status",
            "cpu",
            "memory",
            "battery",
        ],
        "clock": {
            "format": "%Y-%m-%d %H:%M",
            "tooltip": False,
        },
        "cpu": {
            "format": "CPU {usage}%",
            "interval": 5,
        },
        "memory": {
            "format": "RAM {}%",
            "interval": 10,
        },
        "battery": {
            "format":          "BAT {capacity}%",
            "format-charging": "CHG {capacity}%",
            "states": {"warning": 20, "critical": 10},
        },
    }
