"""
compositor_config.py
Generates Hyprland configuration for Luminos compositor layer.

Rules:
- generate_hyprland_config() is pure — returns a string, touches no files.
- write_config() is the only file-writing function.
- All visual values match LUMINOS_DESIGN_SYSTEM.md exactly.
- Zone 2 XWayland windows get blue borders.
- Zone 3 windows get red borders + QUARANTINE title marker.
- Config targets Hyprland on Arch Linux with luminos-ai.service.
"""

import logging
import os

logger = logging.getLogger("luminos-ai.compositor.config")


def generate_hyprland_config(output_name: str = "eDP-1") -> str:
    """
    Generate a Hyprland config string tuned for Luminos.

    Args:
        output_name: Wayland output connector name (e.g. "eDP-1", "HDMI-A-1").

    Returns:
        Multi-line Hyprland config string.
    """
    return f"""\
# Luminos Hyprland Configuration
# Auto-generated by luminos compositor_config.py
# DO NOT edit manually — regenerate via luminos-ai compositor tools

# --- Monitor ---
monitor = {output_name}, preferred, auto, 1

# --- Input ---
input {{
    kb_layout = us
    follow_mouse = 1
    sensitivity = 0
    touchpad {{
        natural_scroll = true
        tap-to-click = true
        disable_while_typing = true
        scroll_factor = 0.8
    }}
}}

# --- Appearance ---
general {{
    gaps_in = 4
    gaps_out = 8
    border_size = 1
    col.active_border = rgba(0080FFaa)
    col.inactive_border = rgba(ffffff10)
    layout = dwindle
}}

decoration {{
    rounding = 12

    blur {{
        enabled = yes
        size = 8
        passes = 2
        new_optimizations = yes
        xray = no
    }}

    shadow {{
        enabled = yes
        range = 20
        render_power = 3
        color = rgba(0033660d)
    }}

    active_opacity = 1.0
    inactive_opacity = 0.95
    dim_inactive = false
}}

animations {{
    enabled = yes

    bezier = luminos, 0.4, 0, 0.2, 1
    bezier = luminosEnter, 0.0, 0, 0.2, 1
    bezier = luminosExit, 0.4, 0, 1, 1

    animation = windows, 1, 2, luminos, slide
    animation = windowsOut, 1, 1.5, luminosExit, slide
    animation = fade, 1, 2, luminos
    animation = workspaces, 1, 2.5, luminos, slidevert
}}

dwindle {{
    pseudotile = true
    preserve_split = true
}}

misc {{
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
}}

# --- Layer Rules (Luminos UI surfaces — blur via compositor) ---
layerrule {{
    name = blur-bar
    match:namespace = ^luminos-bar$
    blur = true
}}

layerrule {{
    name = blur-quick-settings
    match:namespace = ^luminos-quick-settings$
    blur = true
}}

layerrule {{
    name = blur-notification-center
    match:namespace = ^luminos-notification-center$
    blur = true
}}

layerrule {{
    name = blur-calendar
    match:namespace = ^luminos-calendar$
    blur = true
}}

# --- Window rules: maximized (no rounding, no border) ---
windowrulev2 = rounding 0, fullscreen:1
windowrulev2 = noborder, fullscreen:1

# --- Zone 2: Wine/XWayland windows (accent blue border) ---
windowrulev2 = bordercolor rgba(0080FFee), xwayland:1

# --- Zone 3: Quarantine VM windows (error red border + thick) ---
windowrulev2 = bordercolor rgba(FF4455ee), title:^(.*QUARANTINE.*)$
windowrulev2 = bordersize 3, title:^(.*QUARANTINE.*)$

# --- Luminos AI Daemon ---
exec-once = luminos-ai

# --- Luminos Bar + Dock ---
exec-once = luminos-bar
exec-once = luminos-dock

# --- Key bindings ---
$mod = SUPER

bind = $mod, Q, killactive
bind = $mod, Return, exec, foot
bind = $mod, Space, exec, wofi --show drun
bind = $mod SHIFT, E, exit
bind = $mod SHIFT, R, exec, hyprctl reload

# --- Workspaces ---
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5

# --- Window movement ---
bind = $mod, left, movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up, movefocus, u
bind = $mod, down, movefocus, d
bind = $mod SHIFT, left, movewindow, l
bind = $mod SHIFT, right, movewindow, r
bind = $mod SHIFT, up, movewindow, u
bind = $mod SHIFT, down, movewindow, d

# --- Fullscreen ---
bind = $mod, F, fullscreen, 1
"""


# Keep backward compat alias
generate_sway_config = generate_hyprland_config


def write_config(path: str = "~/.config/hypr/hyprland.conf") -> dict:
    """
    Write the generated Hyprland config to disk.

    Args:
        path: Destination file path (tilde expanded).

    Returns:
        {"success": bool, "path": str, "error": str|None}
    """
    expanded = os.path.expanduser(path)
    try:
        os.makedirs(os.path.dirname(expanded), exist_ok=True)
        content = generate_hyprland_config()
        with open(expanded, "w") as f:
            f.write(content)
        logger.info(f"Hyprland config written to {expanded}")
        return {"success": True, "path": expanded, "error": None}
    except OSError as e:
        logger.error(f"Failed to write Hyprland config to {expanded}: {e}")
        return {"success": False, "path": expanded, "error": str(e)}
