#!/bin/bash
# scripts/build_iso.sh
# Phase 6 — Luminos OS ISO Builder (Arch Linux / archiso)
#
# Builds a bootable Luminos OS ISO using archiso.
# Requirements: archiso, chaotic-aur configured (for AUR packages)
#
# Usage:
#   sudo bash scripts/build_iso.sh
#
# Output: build/out/luminos-<version>-x86_64.iso

set -euo pipefail

LUMINOS_VERSION="0.1.0"
LUMINOS_CODENAME="Arch"
BUILD_DATE="$(date +%Y-%m-%d)"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
BUILD_DIR="$REPO_DIR/build"
PROFILE_DIR="$BUILD_DIR/luminos-profile"
WORK_DIR="$BUILD_DIR/work"
OUTPUT_DIR="$BUILD_DIR/out"
LOG="$BUILD_DIR/build.log"
START_TIME="$(date +%s)"

mkdir -p "$BUILD_DIR"

log() { echo "[build_iso] $*" | tee -a "$LOG"; }
die() { log "ERROR: $*"; exit 1; }

log "=== Luminos OS ${LUMINOS_VERSION} ISO Builder ==="
log "Repo: $REPO_DIR"
log "Output: $OUTPUT_DIR/"

# ---------------------------------------------------------------------------
# Dependency check
# ---------------------------------------------------------------------------
check_deps() {
    log "--- Checking dependencies ---"
    local deps=(archiso mtools dosfstools libisoburn squashfs-tools)
    local missing=()
    for dep in "${deps[@]}"; do
        if ! pacman -Qi "$dep" &>/dev/null; then
            missing+=("$dep")
        fi
    done
    if [ "${#missing[@]}" -gt 0 ]; then
        log "Installing missing deps: ${missing[*]}"
        sudo pacman -S --noconfirm --needed "${missing[@]}"
    fi
    log "Dependencies OK"
}

# ---------------------------------------------------------------------------
# Stage 1 — Create archiso profile from releng template
# ---------------------------------------------------------------------------
stage1_profile() {
    log "--- Stage 1: Create archiso profile ---"

    [ -d "$PROFILE_DIR" ] && rm -rf "$PROFILE_DIR"
    cp -r /usr/share/archiso/configs/releng/ "$PROFILE_DIR"

    # Update profiledef.sh
    cat > "$PROFILE_DIR/profiledef.sh" << PROFILEDEF
#!/usr/bin/env bash
# luminos profiledef.sh — generated by build_iso.sh
iso_name="luminos"
iso_label="LUMINOS_${LUMINOS_VERSION//./_}"
iso_publisher="Luminos OS <https://luminos.os>"
iso_application="Luminos OS ${LUMINOS_VERSION}"
iso_version="${LUMINOS_VERSION}"
install_dir="arch"
buildmodes=('iso')
bootmodes=('bios.syslinux.mbr' 'bios.syslinux.eltorito'
           'uefi-ia32.grub.esp' 'uefi-x64.systemd-boot.esp')
arch="x86_64"
pacman_conf="pacman.conf"
airootfs_image_type="squashfs"
airootfs_image_tool_options=('-comp' 'xz' '-Xbcj' 'x86' '-b' '1M' '-Xdict-size' '1M')
PROFILEDEF

    # Append Luminos packages to the releng package list
    cat >> "$PROFILE_DIR/packages.x86_64" << 'PACKAGES'

# ============================================================
# Luminos OS Required Packages
# ============================================================

# --- Base ---
base
linux
linux-firmware
base-devel
zstd
rsync
wget
curl
git
unzip

# --- System ---
networkmanager
pipewire
pipewire-pulse
pipewire-alsa
wireplumber
polkit
xdg-user-dirs
xdg-desktop-portal
xdg-desktop-portal-gtk

# --- ASUS ROG Hardware ---
asusctl
supergfxctl
power-profiles-daemon

# --- NVIDIA (G14 dGPU) ---
nvidia
nvidia-utils
lib32-nvidia-utils
nvidia-settings

# --- AMD GPU / Vulkan ---
mesa
lib32-mesa
vulkan-radeon
lib32-vulkan-radeon
vulkan-icd-loader
lib32-vulkan-icd-loader

# --- Hyprland Desktop ---
hyprland
xdg-desktop-portal-hyprland
qt5-wayland
qt6-wayland
waybar
wofi
dunst
swww
mpvpaper
grim
slurp
foot

# --- Login Manager ---
greetd

# --- Fonts ---
ttf-inter
ttf-jetbrains-mono-nerd
noto-fonts
noto-fonts-emoji

# --- Python ---
python
python-pip
python-gobject
gtk4
libadwaita

# --- Compatibility stack ---
wine
wine-gecko
wine-mono
winetricks
lutris
steam

# --- VM stack ---
qemu-base
libvirt
iptables-nft

# --- Icon extraction ---
icoutils

# --- Misc ---
socat
bc

# --- AI runtime ---
llama-cpp

# --- Build tools (live wallpaper) ---
gcc
wayland-protocols
libdrm
libxkbcommon

PACKAGES

    log "Stage 1 complete"
}

# ---------------------------------------------------------------------------
# Stage 2 — Configure pacman.conf with chaotic-aur
# ---------------------------------------------------------------------------
stage2_pacman() {
    log "--- Stage 2: Configure pacman.conf (chaotic-aur) ---"

    cp /etc/pacman.conf "$PROFILE_DIR/pacman.conf"

    # Add chaotic-aur if not already present
    if ! grep -q "chaotic-aur" "$PROFILE_DIR/pacman.conf"; then
        cat >> "$PROFILE_DIR/pacman.conf" << 'CHAOTIC'

# Chaotic-AUR — pre-built AUR packages
[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist
CHAOTIC
        log "Added chaotic-aur to pacman.conf"
    fi

    log "Stage 2 complete"
}

# ---------------------------------------------------------------------------
# Stage 3 — Build airootfs structure
# ---------------------------------------------------------------------------
stage3_airootfs() {
    log "--- Stage 3: Build airootfs ---"
    local AF="$PROFILE_DIR/airootfs"

    # ---- /etc ----
    mkdir -p "$AF/etc"
    echo "luminos" > "$AF/etc/hostname"
    echo "en_US.UTF-8 UTF-8" > "$AF/etc/locale.gen"
    echo "LANG=en_US.UTF-8" > "$AF/etc/locale.conf"
    ln -sf /usr/share/zoneinfo/UTC "$AF/etc/localtime" 2>/dev/null || true

    # ---- /etc/os-release ----
    cat > "$AF/etc/os-release" << OSRELEASE
NAME="Luminos"
VERSION="${LUMINOS_VERSION}"
ID=luminos
ID_LIKE=arch
PRETTY_NAME="Luminos ${LUMINOS_VERSION}"
HOME_URL="https://luminos.os"
BUILD_ID=rolling
LOGO=luminos
OSRELEASE

    # ---- NVIDIA + Wayland environment ----
    cat > "$AF/etc/environment" << 'ENVFILE'
LIBVA_DRIVER_NAME=nvidia
XDG_SESSION_TYPE=wayland
GBM_BACKEND=nvidia-drm
__GLX_VENDOR_LIBRARY_NAME=nvidia
WLR_NO_HARDWARE_CURSORS=1
MOZ_ENABLE_WAYLAND=1
ELECTRON_OZONE_PLATFORM_HINT=wayland
QT_QPA_PLATFORMTHEME=qt5ct
QT_AUTO_SCREEN_SCALE_FACTOR=1
GTK_THEME=Adwaita:dark
XCURSOR_THEME=Adwaita
XCURSOR_SIZE=24
ENVFILE

    # ---- luminos user via sysusers ----
    mkdir -p "$AF/etc/sysusers.d"
    cat > "$AF/etc/sysusers.d/luminos.conf" << 'SYSUSERS'
u luminos - "Luminos User" /home/luminos /bin/bash
m luminos wheel
m luminos video
m luminos audio
m luminos input
m luminos kvm
m luminos storage
SYSUSERS

    # ---- sudoers ----
    mkdir -p "$AF/etc/sudoers.d"
    echo "%wheel ALL=(ALL:ALL) ALL" > "$AF/etc/sudoers.d/wheel"
    chmod 440 "$AF/etc/sudoers.d/wheel"
    echo "luminos ALL=(ALL) NOPASSWD: ALL" > "$AF/etc/sudoers.d/luminos-live"
    chmod 440 "$AF/etc/sudoers.d/luminos-live"

    # ---- greetd config ----
    mkdir -p "$AF/etc/greetd"
    cat > "$AF/etc/greetd/config.toml" << 'GREETD'
[terminal]
vt = 1

[default_session]
command = "luminos-greeter"
user = "greeter"
GREETD

    # ---- systemd services ----
    mkdir -p "$AF/etc/systemd/system"
    local WANTS="$AF/etc/systemd/system/multi-user.target.wants"
    mkdir -p "$WANTS"

    cp "$REPO_DIR/systemd/luminos-ai.service"       "$AF/etc/systemd/system/"
    cp "$REPO_DIR/systemd/luminos-sentinel.service"  "$AF/etc/systemd/system/"

    ln -sf /usr/lib/systemd/system/NetworkManager.service  "$WANTS/"
    ln -sf /usr/lib/systemd/system/asusd.service           "$WANTS/" 2>/dev/null || true
    ln -sf /usr/lib/systemd/system/supergfxd.service       "$WANTS/" 2>/dev/null || true
    ln -sf /usr/lib/systemd/system/greetd.service          "$WANTS/"
    ln -sf /etc/systemd/system/luminos-ai.service          "$WANTS/"

    # ---- Copy logrotate config ----
    mkdir -p "$AF/etc/logrotate.d"
    cp "$REPO_DIR/config/logrotate-luminos" "$AF/etc/logrotate.d/luminos"

    # ---- /opt/luminos — Luminos source ----
    mkdir -p "$AF/opt/luminos"
    rsync -a --exclude=build --exclude=.git --exclude='__pycache__' \
        --exclude='*.pyc' --exclude='*.egg-info' \
        "$REPO_DIR/" "$AF/opt/luminos/"

    # ---- Version file ----
    cat > "$AF/opt/luminos/version.py" << VERSIONPY
# Luminos OS version — generated by build_iso.sh
LUMINOS_VERSION   = "${LUMINOS_VERSION}"
LUMINOS_CODENAME  = "${LUMINOS_CODENAME}"
LUMINOS_BUILD_DATE = "${BUILD_DATE}"
LUMINOS_BASE      = "Arch Linux"
VERSIONPY

    # ---- /usr/local/bin — launcher scripts ----
    mkdir -p "$AF/usr/local/bin"

    _make_launcher() {
        local name="$1"
        local module="$2"
        cat > "$AF/usr/local/bin/$name" << LAUNCHER
#!/bin/bash
exec python3 -c "import sys; sys.path.insert(0, '/opt/luminos/src'); import ${module}; ${module}.main()" "\$@"
LAUNCHER
        chmod +x "$AF/usr/local/bin/$name"
    }

    # Session script
    cp "$REPO_DIR/scripts/luminos-session.sh" "$AF/usr/local/bin/luminos-session"
    chmod +x "$AF/usr/local/bin/luminos-session"

    # Python GUI launchers
    for pair in \
        "luminos-bar:gui.bar.bar_app" \
        "luminos-dock:gui.dock.dock_app" \
        "luminos-settings:gui.settings.settings_app" \
        "luminos-firstrun:gui.firstrun.firstrun_app" \
        "luminos-greeter:gui.greeter.greeter_app" \
        "luminos-launcher:gui.launcher.launcher_app" \
        "luminos-run-windows:classifier.launch" \
        "luminos-compat-log:gui.compat_log_viewer"; do
        name="${pair%%:*}"
        module="${pair#*:}"
        cat > "$AF/usr/local/bin/$name" << LAUNCHER
#!/bin/bash
export PYTHONPATH=/opt/luminos/src
exec python3 -m ${module} "\$@"
LAUNCHER
        chmod +x "$AF/usr/local/bin/$name"
    done

    # GPU init
    cat > "$AF/usr/local/bin/luminos-gpu-init" << 'GPUINIT'
#!/bin/bash
supergfxctl --mode Hybrid 2>/dev/null || true
GPUINIT
    chmod +x "$AF/usr/local/bin/luminos-gpu-init"

    # GPU init service
    cat > "$AF/etc/systemd/system/luminos-gpu-init.service" << 'GPUSERVICE'
[Unit]
Description=Luminos GPU Hybrid Mode Init
After=supergfxd.service
Requires=supergfxd.service

[Service]
Type=oneshot
ExecStart=/usr/local/bin/luminos-gpu-init
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
GPUSERVICE
    ln -sf /etc/systemd/system/luminos-gpu-init.service "$WANTS/"

    # ---- /usr/share/wayland-sessions ----
    mkdir -p "$AF/usr/share/wayland-sessions"
    cat > "$AF/usr/share/wayland-sessions/luminos.desktop" << 'SESSION'
[Desktop Entry]
Name=Luminos
Comment=Luminos OS Desktop Session
Exec=/usr/local/bin/luminos-session
Type=Application
SESSION

    # ---- Hyprland config ----
    mkdir -p "$AF/etc/skel/.config/hypr"
    if [ -d "$REPO_DIR/config/hypr" ]; then
        cp -r "$REPO_DIR/config/hypr/"* "$AF/etc/skel/.config/hypr/" 2>/dev/null || true
    fi

    # ---- Default wallpapers dir ----
    mkdir -p "$AF/usr/share/luminos/wallpapers"

    log "Stage 3 complete"
}

# ---------------------------------------------------------------------------
# Stage 4 — customize_airootfs.sh hook
# ---------------------------------------------------------------------------
stage4_customize_hook() {
    log "--- Stage 4: customize_airootfs.sh hook ---"

    cat > "$PROFILE_DIR/airootfs.sh" << 'HOOK'
#!/usr/bin/env bash
# Runs inside the built airootfs chroot after package installation.
set -e

# Locale
locale-gen

# Set up luminos user home
if ! id luminos &>/dev/null; then
    useradd -m -G wheel,video,audio,input,storage,kvm luminos
fi
# No password for live session — first run wizard sets it
passwd -d luminos

# Compile live wallpaper if sources present
WALLPAPER_SRC="/opt/luminos/src/live_wallpaper"
if [ -f "$WALLPAPER_SRC/Makefile" ]; then
    make -C "$WALLPAPER_SRC" 2>/dev/null || true
    if [ -f "$WALLPAPER_SRC/luminos-live-wallpaper" ]; then
        cp "$WALLPAPER_SRC/luminos-live-wallpaper" /usr/local/bin/
        chmod +x /usr/local/bin/luminos-live-wallpaper
    fi
fi

# Set GPU to Hybrid mode at first boot
systemctl enable luminos-gpu-init.service 2>/dev/null || true
systemctl enable luminos-ai.service       2>/dev/null || true

HOOK
    chmod +x "$PROFILE_DIR/airootfs.sh"

    log "Stage 4 complete"
}

# ---------------------------------------------------------------------------
# Stage 5 — Build ISO with mkarchiso
# ---------------------------------------------------------------------------
stage5_build() {
    log "--- Stage 5: Build ISO ---"
    mkdir -p "$WORK_DIR" "$OUTPUT_DIR"

    mkarchiso -v \
        -w "$WORK_DIR" \
        -o "$OUTPUT_DIR" \
        "$PROFILE_DIR" \
        2>&1 | tee -a "$LOG"

    log "Stage 5 complete"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
check_deps
stage1_profile
stage2_pacman
stage3_airootfs
stage4_customize_hook
stage5_build

END_TIME="$(date +%s)"
ELAPSED="$((END_TIME - START_TIME))"
ISO_FILE="$(ls -t "$OUTPUT_DIR"/*.iso 2>/dev/null | head -1 || echo '')"

log ""
log "=== BUILD COMPLETE ==="
if [ -n "$ISO_FILE" ]; then
    ISO_SIZE="$(du -sh "$ISO_FILE" | cut -f1)"
    log "ISO:  $ISO_FILE"
    log "Size: $ISO_SIZE"
    log "SHA256: $(sha256sum "$ISO_FILE" | cut -d' ' -f1)"
fi
log "Time: $((ELAPSED/60))m $((ELAPSED%60))s"
log "Log:  $LOG"
log ""
log "Test with QEMU:"
log "  qemu-system-x86_64 -enable-kvm -m 4G -boot d \\"
log "    -cdrom $ISO_FILE \\"
log "    -vga virtio -display sdl"
